[package]
name = "vector_math"
version = "0.1.0"
edition = "2021"
authors = ["Omar M.Gindia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
